# Generated by Django 5.0.4 on 2024-12-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizacion',
            name='Sistema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
